### PR TITLE
Function attributes

### PR DESCRIPTION
**Pull request by dkfellows**
This makes some simple parts of spin1api be inlined (where they're trivial wrappers around sark), and adds [GCC function attributes](https://gcc.gnu.org/onlinedocs/gcc/Common-Function-Attributes.html) to quite a few spin1api and sark functions. Apart from inlining control these are:

 * `malloc` — the result of this function (if not `NULL`) aliases no other memory
 * `alloc_size` — the annotated argument(s) give an allocation size
 * `assume_aligned` — specifies the alignment of the result
 * `nonnull` — the pointer arguments must not be `NULL`
 * `noreturn` — the function does not return (e.g., `rt_error()`).

### CODE REVIEW

**Comment by dkfellows** [comment]
If we support building with the ARM compiler, someone will have to check this for me.

**Comment by rowleya** [comment]
It compiles, but it does raise warnings about assume_aligned and alloc_size.  I think there might be equivalents:
http://infocenter.arm.com/help/index.jsp?topic=/com.arm.doc.dui0491f/Cacjcjce.html

**Review by rowleya — APPROVED** [review]
Seems reasonable to me.  Running a test to ensure that this doesn't break any existing code then will merge.

**Comment by rowleya** [comment]
Almost merged but checked with the arm compiler and it gives lots of warnings:
```
$ make GNU=0
make[1]: Entering directory `/c/Users/zzalsar4/git/spinnaker_tools/sark'
mkdir -p ../build/arm
cp sark_alib.s ../build/arm/sark_alib.s
mkdir -p ../build/arm
/c/Users/zzalsar4/git/spinnaker_tools/tools/h2asm /c/Users/zzalsar4/git/spinnaker_tools/include/spinnaker.h > ../build/arm/spinnaker.s
mkdir -p ../build/arm
/c/Users/zzalsar4/git/spinnaker_tools/tools/h2asm /c/Users/zzalsar4/git/spinnaker_tools/include/sark.h > ../build/arm/sark.s
mkdir -p ../build/arm
armasm --keep --cpu=5te --apcs interwork -o ../build/arm/sark_alib.o ../build/arm/sark_alib.s
"../build/arm/sark_alib.s", line 777: Warning: A1581W: Added 2 bytes of padding at address 0xe
  777 00000010    area  alib_chksum, readonly, code
0 Errors, 1 Warning
armcc -c --c99 --cpu=5te --apcs interwork --min_array_alignment=4 -I /c/Users/zzalsar4/git/spinnaker_tools/include --thumb -DTHUMB --split_sections -g -DSARK_API -Ospace -o ../build/arm/sark_base.o sark_base.c
"c:/Users/zzalsar4/git/spinnaker_tools/include/sark.h", line 1844: Warning:  #1207-D: attribute "alloc_size" ignored
  __attribute__((malloc, alloc_size(1, 2), assume_aligned(4))) void *
                         ^
"c:/Users/zzalsar4/git/spinnaker_tools/include/sark.h", line 1844: Warning:  #1207-D: attribute "assume_aligned" ignored
  __attribute__((malloc, alloc_size(1, 2), assume_aligned(4))) void *
                                           ^
"c:/Users/zzalsar4/git/spinnaker_tools/include/sark.h", line 1885: Warning:  #1207-D: attribute "alloc_size" ignored
  __attribute__((malloc, alloc_size(2), assume_aligned(4))) void *
                         ^
"c:/Users/zzalsar4/git/spinnaker_tools/include/sark.h", line 1885: Warning:  #1207-D: attribute "assume_aligned" ignored
  __attribute__((malloc, alloc_size(2), assume_aligned(4))) void *
                                        ^
"c:/Users/zzalsar4/git/spinnaker_tools/include/spin1_api.h", line 414: Warning:  #1207-D: attribute "alloc_size" ignored
  static inline __attribute__((alloc_size(1), malloc, assume_aligned(4))) void*
                               ^
"c:/Users/zzalsar4/git/spinnaker_tools/include/spin1_api.h", line 414: Warning:  #1207-D: attribute "assume_aligned" ignored
  static inline __attribute__((alloc_size(1), malloc, assume_aligned(4))) void*
                                                      ^
sark_base.c: 6 warnings, 0 errors
armcc -c --c99 --cpu=5te --apcs interwork --min_array_alignment=4 -I /c/Users/zzalsar4/git/spinnaker_tools/include --thumb -DTHUMB --split_sections -g -DSARK_API -Ospace -o ../build/arm/sark_event.o sark_event.c
"c:/Users/zzalsar4/git/spinnaker_tools/include/sark.h", line 1844: Warning:  #1207-D: attribute "alloc_size" ignored
  __attribute__((malloc, alloc_size(1, 2), assume_aligned(4))) void *
                         ^
"c:/Users/zzalsar4/git/spinnaker_tools/include/sark.h", line 1844: Warning:  #1207-D: attribute "assume_aligned" ignored
  __attribute__((malloc, alloc_size(1, 2), assume_aligned(4))) void *
                                           ^
"c:/Users/zzalsar4/git/spinnaker_tools/include/sark.h", line 1885: Warning:  #1207-D: attribute "alloc_size" ignored
  __attribute__((malloc, alloc_size(2), assume_aligned(4))) void *
                         ^
"c:/Users/zzalsar4/git/spinnaker_tools/include/sark.h", line 1885: Warning:  #1207-D: attribute "assume_aligned" ignored
  __attribute__((malloc, alloc_size(2), assume_aligned(4))) void *
                                        ^
sark_event.c: 4 warnings, 0 errors
armcc -c --c99 --cpu=5te --apcs interwork --min_array_alignment=4 -I /c/Users/zzalsar4/git/spinnaker_tools/include --thumb -DTHUMB --split_sections -g -DSARK_API -Ospace -o ../build/arm/sark_timer.o sark_timer.c
"c:/Users/zzalsar4/git/spinnaker_tools/include/sark.h", line 1844: Warning:  #1207-D: attribute "alloc_size" ignored
  __attribute__((malloc, alloc_size(1, 2), assume_aligned(4))) void *
                         ^
"c:/Users/zzalsar4/git/spinnaker_tools/include/sark.h", line 1844: Warning:  #1207-D: attribute "assume_aligned" ignored
  __attribute__((malloc, alloc_size(1, 2), assume_aligned(4))) void *
                                           ^
"c:/Users/zzalsar4/git/spinnaker_tools/include/sark.h", line 1885: Warning:  #1207-D: attribute "alloc_size" ignored
  __attribute__((malloc, alloc_size(2), assume_aligned(4))) void *
                         ^
"c:/Users/zzalsar4/git/spinnaker_tools/include/sark.h", line 1885: Warning:  #1207-D: attribute "assume_aligned" ignored
  __attribute__((malloc, alloc_size(2), assume_aligned(4))) void *
                                        ^
sark_timer.c: 4 warnings, 0 errors
armcc -c --c99 --cpu=5te --apcs interwork --min_array_alignment=4 -I /c/Users/zzalsar4/git/spinnaker_tools/include --thumb -DTHUMB --split_sections -g -DSARK_API -Ospace -o ../build/arm/sark_hw.o sark_hw.c
"c:/Users/zzalsar4/git/spinnaker_tools/include/sark.h", line 1844: Warning:  #1207-D: attribute "alloc_size" ignored
  __attribute__((malloc, alloc_size(1, 2), assume_aligned(4))) void *
                         ^
"c:/Users/zzalsar4/git/spinnaker_tools/include/sark.h", line 1844: Warning:  #1207-D: attribute "assume_aligned" ignored
  __attribute__((malloc, alloc_size(1, 2), assume_aligned(4))) void *
                                           ^
"c:/Users/zzalsar4/git/spinnaker_tools/include/sark.h", line 1885: Warning:  #1207-D: attribute "alloc_size" ignored
  __attribute__((malloc, alloc_size(2), assume_aligned(4))) void *
                         ^
"c:/Users/zzalsar4/git/spinnaker_tools/include/sark.h", line 1885: Warning:  #1207-D: attribute "assume_aligned" ignored
  __attribute__((malloc, alloc_size(2), assume_aligned(4))) void *
                                        ^
sark_hw.c: 4 warnings, 0 errors
armcc -c --c99 --cpu=5te --apcs interwork --min_array_alignment=4 -I /c/Users/zzalsar4/git/spinnaker_tools/include --split_sections -g -DSARK_API -Ospace -o ../build/arm/sark_isr.o sark_isr.c
"c:/Users/zzalsar4/git/spinnaker_tools/include/sark.h", line 1844: Warning:  #1207-D: attribute "alloc_size" ignored
  __attribute__((malloc, alloc_size(1, 2), assume_aligned(4))) void *
                         ^
"c:/Users/zzalsar4/git/spinnaker_tools/include/sark.h", line 1844: Warning:  #1207-D: attribute "assume_aligned" ignored
  __attribute__((malloc, alloc_size(1, 2), assume_aligned(4))) void *
                                           ^
"c:/Users/zzalsar4/git/spinnaker_tools/include/sark.h", line 1885: Warning:  #1207-D: attribute "alloc_size" ignored
  __attribute__((malloc, alloc_size(2), assume_aligned(4))) void *
                         ^
"c:/Users/zzalsar4/git/spinnaker_tools/include/sark.h", line 1885: Warning:  #1207-D: attribute "assume_aligned" ignored
  __attribute__((malloc, alloc_size(2), assume_aligned(4))) void *
                                        ^
sark_isr.c: 4 warnings, 0 errors
armcc -c --c99 --cpu=5te --apcs interwork --min_array_alignment=4 -I /c/Users/zzalsar4/git/spinnaker_tools/include --thumb -DTHUMB --split_sections -g -DSARK_API -Ospace -o ../build/arm/sark_alloc.o sark_alloc.c
"c:/Users/zzalsar4/git/spinnaker_tools/include/sark.h", line 1844: Warning:  #1207-D: attribute "alloc_size" ignored
  __attribute__((malloc, alloc_size(1, 2), assume_aligned(4))) void *
                         ^
"c:/Users/zzalsar4/git/spinnaker_tools/include/sark.h", line 1844: Warning:  #1207-D: attribute "assume_aligned" ignored
  __attribute__((malloc, alloc_size(1, 2), assume_aligned(4))) void *
                                           ^
"c:/Users/zzalsar4/git/spinnaker_tools/include/sark.h", line 1885: Warning:  #1207-D: attribute "alloc_size" ignored
  __attribute__((malloc, alloc_size(2), assume_aligned(4))) void *
                         ^
"c:/Users/zzalsar4/git/spinnaker_tools/include/sark.h", line 1885: Warning:  #1207-D: attribute "assume_aligned" ignored
  __attribute__((malloc, alloc_size(2), assume_aligned(4))) void *
                                        ^
"sark_alloc.c", line 50: Warning: C3017W: cpsr may be used before being set
    uint cpsr;
         ^
"sark_alloc.c", line 132: Warning: C3017W: cpsr may be used before being set
    uint cpsr;
         ^
"sark_alloc.c", line 234: Warning: C3017W: cpsr may be used before being set
    uint cpsr;
         ^
sark_alloc.c: 7 warnings, 0 errors
armcc -c --c99 --cpu=5te --apcs interwork --min_array_alignment=4 -I /c/Users/zzalsar4/git/spinnaker_tools/include --thumb -DTHUMB --split_sections -g -DSARK_API -Ospace -o ../build/arm/sark_io.o sark_io.c
"c:/Users/zzalsar4/git/spinnaker_tools/include/sark.h", line 1844: Warning:  #1207-D: attribute "alloc_size" ignored
  __attribute__((malloc, alloc_size(1, 2), assume_aligned(4))) void *
                         ^
"c:/Users/zzalsar4/git/spinnaker_tools/include/sark.h", line 1844: Warning:  #1207-D: attribute "assume_aligned" ignored
  __attribute__((malloc, alloc_size(1, 2), assume_aligned(4))) void *
                                           ^
"c:/Users/zzalsar4/git/spinnaker_tools/include/sark.h", line 1885: Warning:  #1207-D: attribute "alloc_size" ignored
  __attribute__((malloc, alloc_size(2), assume_aligned(4))) void *
                         ^
"c:/Users/zzalsar4/git/spinnaker_tools/include/sark.h", line 1885: Warning:  #1207-D: attribute "assume_aligned" ignored
  __attribute__((malloc, alloc_size(2), assume_aligned(4))) void *
                                        ^
sark_io.c: 4 warnings, 0 errors
armcc -c --c99 --cpu=5te --apcs interwork --min_array_alignment=4 -I /c/Users/zzalsar4/git/spinnaker_tools/include --thumb -DTHUMB --split_sections -g -DSARK_API -Ospace -o ../build/arm/sark_pkt.o sark_pkt.c
"c:/Users/zzalsar4/git/spinnaker_tools/include/sark.h", line 1844: Warning:  #1207-D: attribute "alloc_size" ignored
  __attribute__((malloc, alloc_size(1, 2), assume_aligned(4))) void *
                         ^
"c:/Users/zzalsar4/git/spinnaker_tools/include/sark.h", line 1844: Warning:  #1207-D: attribute "assume_aligned" ignored
  __attribute__((malloc, alloc_size(1, 2), assume_aligned(4))) void *
                                           ^
"c:/Users/zzalsar4/git/spinnaker_tools/include/sark.h", line 1885: Warning:  #1207-D: attribute "alloc_size" ignored
  __attribute__((malloc, alloc_size(2), assume_aligned(4))) void *
                         ^
"c:/Users/zzalsar4/git/spinnaker_tools/include/sark.h", line 1885: Warning:  #1207-D: attribute "assume_aligned" ignored
  __attribute__((malloc, alloc_size(2), assume_aligned(4))) void *
                                        ^
sark_pkt.c: 4 warnings, 0 errors
armcc -c --c99 --cpu=5te --apcs interwork --min_array_alignment=4 -I /c/Users/zzalsar4/git/spinnaker_tools/include --split_sections -g -DSARK_API -Ospace -o ../build/arm/sark_div0.o sark_div0.c
"c:/Users/zzalsar4/git/spinnaker_tools/include/sark.h", line 1844: Warning:  #1207-D: attribute "alloc_size" ignored
  __attribute__((malloc, alloc_size(1, 2), assume_aligned(4))) void *
                         ^
"c:/Users/zzalsar4/git/spinnaker_tools/include/sark.h", line 1844: Warning:  #1207-D: attribute "assume_aligned" ignored
  __attribute__((malloc, alloc_size(1, 2), assume_aligned(4))) void *
                                           ^
"c:/Users/zzalsar4/git/spinnaker_tools/include/sark.h", line 1885: Warning:  #1207-D: attribute "alloc_size" ignored
  __attribute__((malloc, alloc_size(2), assume_aligned(4))) void *
                         ^
"c:/Users/zzalsar4/git/spinnaker_tools/include/sark.h", line 1885: Warning:  #1207-D: attribute "assume_aligned" ignored
  __attribute__((malloc, alloc_size(2), assume_aligned(4))) void *
                                        ^
sark_div0.c: 4 warnings, 0 errors
rm -f /c/Users/zzalsar4/git/spinnaker_tools/lib/sark.a
armar -rsc /c/Users/zzalsar4/git/spinnaker_tools/lib/sark.a ../build/arm/sark_alib.o ../build/arm/sark_base.o ../build/arm/sark_event.o ../build/arm/sark_timer.o ../build/arm/sark_hw.o ../build/arm/sark_isr.o ../build/arm/sark_alloc.o ../build/arm/sark_io.o ../build/arm/sark_pkt.o ../build/arm/sark_div0.o
make[1]: Leaving directory `/c/Users/zzalsar4/git/spinnaker_tools/sark'
make[1]: Entering directory `/c/Users/zzalsar4/git/spinnaker_tools/spin1_api'
make[2]: Entering directory `/c/Users/zzalsar4/git/spinnaker_tools/sark'
rm -f ../build/arm/sark.o
armlink --partial -o ../build/arm/sark.o ../build/arm/sark_alib.o ../build/arm/sark_base.o ../build/arm/sark_event.o ../build/arm/sark_timer.o ../build/arm/sark_hw.o ../build/arm/sark_isr.o ../build/arm/sark_alloc.o ../build/arm/sark_io.o ../build/arm/sark_pkt.o ../build/arm/sark_div0.o
make[2]: Leaving directory `/c/Users/zzalsar4/git/spinnaker_tools/sark'
armcc -c --c99 --cpu=5te --apcs interwork --min_array_alignment=4 -I /c/Users/zzalsar4/git/spinnaker_tools/include --thumb -DTHUMB --split_sections -g -Ospace -o ../build/arm/spin1_api.o spin1_api.c
"c:/Users/zzalsar4/git/spinnaker_tools/include/sark.h", line 1844: Warning:  #1207-D: attribute "alloc_size" ignored
  __attribute__((malloc, alloc_size(1, 2), assume_aligned(4))) void *
                         ^
"c:/Users/zzalsar4/git/spinnaker_tools/include/sark.h", line 1844: Warning:  #1207-D: attribute "assume_aligned" ignored
  __attribute__((malloc, alloc_size(1, 2), assume_aligned(4))) void *
                                           ^
"c:/Users/zzalsar4/git/spinnaker_tools/include/sark.h", line 1885: Warning:  #1207-D: attribute "alloc_size" ignored
  __attribute__((malloc, alloc_size(2), assume_aligned(4))) void *
                         ^
"c:/Users/zzalsar4/git/spinnaker_tools/include/sark.h", line 1885: Warning:  #1207-D: attribute "assume_aligned" ignored
  __attribute__((malloc, alloc_size(2), assume_aligned(4))) void *
                                        ^
"c:/Users/zzalsar4/git/spinnaker_tools/include/spin1_api.h", line 414: Warning:  #1207-D: attribute "alloc_size" ignored
  static inline __attribute__((alloc_size(1), malloc, assume_aligned(4))) void*
                               ^
"c:/Users/zzalsar4/git/spinnaker_tools/include/spin1_api.h", line 414: Warning:  #1207-D: attribute "assume_aligned" ignored
  static inline __attribute__((alloc_size(1), malloc, assume_aligned(4))) void*
                                                      ^
"spin1_api.c", line 814: Warning: C3017W: lr may be used before being set
    register uint lr __asm("lr");
                  ^
spin1_api.c: 7 warnings, 0 errors
armcc -c --c99 --cpu=5te --apcs interwork --min_array_alignment=4 -I /c/Users/zzalsar4/git/spinnaker_tools/include --split_sections -g -Ospace -o ../build/arm/spin1_isr.o spin1_isr.c
"c:/Users/zzalsar4/git/spinnaker_tools/include/sark.h", line 1844: Warning:  #1207-D: attribute "alloc_size" ignored
  __attribute__((malloc, alloc_size(1, 2), assume_aligned(4))) void *
                         ^
"c:/Users/zzalsar4/git/spinnaker_tools/include/sark.h", line 1844: Warning:  #1207-D: attribute "assume_aligned" ignored
  __attribute__((malloc, alloc_size(1, 2), assume_aligned(4))) void *
                                           ^
"c:/Users/zzalsar4/git/spinnaker_tools/include/sark.h", line 1885: Warning:  #1207-D: attribute "alloc_size" ignored
  __attribute__((malloc, alloc_size(2), assume_aligned(4))) void *
                         ^
"c:/Users/zzalsar4/git/spinnaker_tools/include/sark.h", line 1885: Warning:  #1207-D: attribute "assume_aligned" ignored
  __attribute__((malloc, alloc_size(2), assume_aligned(4))) void *
                                        ^
"c:/Users/zzalsar4/git/spinnaker_tools/include/spin1_api.h", line 414: Warning:  #1207-D: attribute "alloc_size" ignored
  static inline __attribute__((alloc_size(1), malloc, assume_aligned(4))) void*
                               ^
"c:/Users/zzalsar4/git/spinnaker_tools/include/spin1_api.h", line 414: Warning:  #1207-D: attribute "assume_aligned" ignored
  static inline __attribute__((alloc_size(1), malloc, assume_aligned(4))) void*
                                                      ^
spin1_isr.c: 6 warnings, 0 errors
rm -f /c/Users/zzalsar4/git/spinnaker_tools/lib/spin1_api.a
armar -rsc /c/Users/zzalsar4/git/spinnaker_tools/lib/spin1_api.a ../build/arm/sark.o ../build/arm/spin1_api.o ../build/arm/spin1_isr.o
make[1]: Leaving directory `/c/Users/zzalsar4/git/spinnaker_tools/spin1_api'
```

**Comment by dkfellows** [comment]
That should fix those extra warnings.

**Pull request merged**
