### PR TITLE
Add basic setup and makefile usage instructions.

### PR DESCRIPTION
**Pull request by mossblaser**
Specifically point at where the cross compiler can be found and provide a very
quick introduction to compiling SpiNNaker applications using the provided
makefiles.

### CODE REVIEW

**Comment by alan-stokes** [comment]
Howdi,

so had a look at this pull request, and am happy with the makefile.example, but not sure (meaning im not sure if its me just being silly or not) about the README.md. reasoning is below:

I'm not sure, but id like to keep everything in one place, and so wouldnt this README.md become a wiki page in the SpiNNakerManchester.github.io wiki module itself (under say 2.7: Native SpiNNaker Application Libraries) and therefore keeping all wiki pages avilable from one place? 

i think that the README.md points to a installation page that resides on the old spinnaker wiki, would it be possible to migrate that over to the github wiki pages as well..... maybe under 0.4 (or moving lienence agreement up to 0.4 and making this "0.3 Installing the Code Sourcery ARM cross compiler"?

opinions?

**Comment by mundya** [comment]
FWIW I think the readme should stay, not least because if I check out the repository then I have a local copy of the instructions.

**Comment by mossblaser** [comment]
I'm afraid I feel fairly strongly in agreement with Andrew that a README
such as this should be included in the project repository. In addition to
Andrew's reasoning, upon a new user being told "you need this [link to
repo]" there is otherwise absolutely no information about what you need to
do. Certainly, I would not guess that you should go to
http://spinnakermanchester.github.io/, click the "view repo", then look in
a github wiki and then find the relevent page amongst the many unrelated
pages.

Re pointing at the wiki: I presume, pointing at "
https://github.com/SpiNNakerManchester/SpiNNakerManchester.github.io/wiki/1.3-C-Development-for-SpiNNaker"
would be the most appropriate place?

I wasn't aware the old wiki had been deprecated -- would it be possible to
port over its contents and to put a prominent link to the new wiki there?
(And update other APT/CS pages accordingly) Further, adding a generic "For
all documentation, see our wiki" link on the
http://spinnakermanchester.github.io/ landing page would be a very good
idea.

**Comment by alan-stokes** [comment]
HI Mundy and Jonathan, 

unfortantely I completelty disagree with your arguement of keeping a indivudal readme in the repos. The correct way would then to put all the wiki pages in the assoicated repo's which would be more confusing to end users to figure out where they need to go to find out the information.

We've currently kept everything aossicated with the software on the github.io wiki, as that's the central place for all end users to go to locate the data they're looking for. You can actually clone that wiki repos and use it offline, and therefore  having it in a local individual place. 

The readme contains stuff thats either already covered in the installation page on 0.2 and 1.3 or should be covered in those. If you using it as a "basic training on how to create code thats runs on spinnaker without the tools" then i'd still says it goes on the github wiki as 2.7 

If your an end user and have spent all your time learning how to install the tools and read the wiki pages on making new models/injection/liveoutput/rerunning/visualising/etc and then you get told "oh theres another guide hiding away in this repos" then thats confusing. 

But as it seems neither of us will be in agreement, ill leave the pull request till Rowley comes back and he can make a judgment call.

**Comment by mossblaser** [comment]
Your argument re: keeping things all in one place does indeed seem sensible!

It sounds to me like the right thing to do would be to strip down the
README to little more than a one-sentence "what is this repo" and a link to
the appropriate Wiki Pages. The wiki pages can then simply receive some
minor updates to include all the advice that was in the README in this PR.

Does that seem sensible?

**Comment by alan-stokes** [comment]
I concur

**Comment by mossblaser** [comment]
Awaiting review from @alan-stokes.

The following Wiki page now holds the information previously in the README: https://github.com/SpiNNakerManchester/SpiNNakerManchester.github.io/wiki/1.3-C-Development-for-SpiNNaker

**Pull request merged**
