### PR TITLE
sdp p2p fix

### PR DESCRIPTION
**Pull request by lplana**
The order of steps 'send p2p packet' and 'schedule timeout' in p2p_send_msg was inverted to avoid a race when interrupts happen between the two steps: the acknowledge packet can arrive before the timeout is scheduled, with the possibility of a spurious timeout occuring.

### CODE REVIEW

**Comment by mossblaser** [comment]
(As discussed offline)

This looks good to me!

I've tried this out on a handful of boards and it does appear to significantly improve reliability when using windowing to non-Ethernet-connected chips. Unfortunately, an (apparently unrelated) issue is still causing occasional crashes/timeouts when reading/writing with many outstanding connections. As such, this change isn't sufficient to start using windowing but makes a reasonable standalone bugfix.

**Comment by mundya** [comment]
> I've tried this out on a handful of boards and it does appear to significantly improve reliability when using windowing to non-Ethernet-connected chips.

This is pleasing news!

**Comment by lplana** [comment]
The latest commit seems to fix the unreliability with windowing to non-Ethernet-connected chips. I have run a limited set of tests and I have not seen it fail with windows of up to 8 SDP messages. sc&mp lacks resources to go beyond 8. My tests also show diminishing returns with windows larger than 4 messages. I have also tested sending internal (chip-to-chip) SDP messages using windowing (up to 8 SDP messages) without any faults.

**Comment by rowleya** [comment]
I have also done some testing of this, and it seems to be good.  I noted that the SpiNNMan default TTO of 640ms didn't allow it to run as fast as when it was reverted back to the boot default of 2560ms.  Otherwise, I could still get ~33Mb/s reads from an Ethernet chip and am now getting ~9Mb/s reads from other chips.

**Comment by lplana** [comment]
I'm re-activating this pull request because I believe that the bug related to SDP windowing is now fixed.

I've tested the fix with host <-> SpiNNaker SDP traffic with up to a wndow of 8 SDP messages without failure.

The tests were conducted in a 3-board toroid, with connections to chips (0,0), (1,1), (4,8), (6,6), (8,4) and (3,11). The tests used the 3 Ethernet ports, one at a time. These chips represent Ethernet-connected chips, a chip 1 hop away, a chip several hops away, and a chip 6 hops away - through 2 spiNNlinks.

I also tested sending to a chip concurrently through 2 different Ethernet ports. The test worked correctly with a window of up to 8 SDP messages, but I think this is still fragile because there is no good solution to running out of free SDP message buffers or free events.

**Comment by mossblaser** [comment]
This is exciting to hear! What sort of throughput are you getting these
days?

**Comment by lplana** [comment]
Hi Jonathan,

Good to hear from you! I hope everything's going well.

No big throughput improvement, mainly reliability. One step at a time.

The latest measurements (write/read):
3.1.0 master
------------
chip        1-window             8-window
0,0     11.70/10.74 Mb/s     32.31/27.58 Mb/s
1,1      5.26/ 5.05 Mb/s          broken
6,6      4.40/ 4.32 Mb/s          broken

3.1.0 sdp_p2p_fix
-----------------
chip        1-window             8-window
0,0     11.70/10.73 Mb/s     32.94/27.87 Mb/s
1,1      5.25/ 5.03 Mb/s      8.72/ 9.14 Mb/s
6,6      4.25/ 4.50 Mb/s      7.60/ 7.91 Mb/s

------------------------------------------------------------------

**Comment by lplana** [comment]
@rowleya, you reported throughput measurements with an earlier fix (20/09/2016). Do you think that you could repeat your tests with this one? It would be great to have an independent check. Hopefully it won't require a lot of your precious time. The changes with respect to master are really very simple, amounting to a handful of lines in a single file.

**Comment by rowleya** [comment]
I will have a go and see what happens...

**Comment by rowleya** [comment]
I can get very similar performance with SpiNNMan:

3.1.0 master
------------
chip    1-window               8-window
0,0      6.54 / 7.99 Mb/s     26.93 / 27.00 Mb/s
1,1      3.76 / 4.07 Mb/s     broken
6,6      3.24 / 3.80 Mb/s     broken

3.1.0 sdp_p2p_fix
-----------------
chip   1-window               8-window
0,0     6.66 / 7.93 Mb/s     26.56 / 26.74 Mb/s
1,1     3.83 / 4.03 Mb/s     9.47 / 10.15 Mb/s
6,6     3.37 / 3.87 Mb/s     8.25 / 8.78 Mb/s

Happy for this to be merged from my point of view

**Pull request merged**
