### PR TITLE
Gnu scamp makefile

### PR DESCRIPTION
**Pull request by rowleya**
Makes it possible to compile scamp using only GNU tools (tested on Windows and linux).  This now appears to boot, with the only issue being that when booting using the version built on linux with the codesourcery tools 4.7.3, it only boots the first chip.  You may want to test with a later version of the tools on linux before merging.

Also fixed a couple of issues in ybug (that I probably introduced at some point).

Note that this is a pull to the merged branch, not master yet.

### CODE REVIEW

**Comment by mossblaser** [comment]
Did ST/Luis ever get a chance to look at this by the way? My checks for
stability have only been very cursory...

**Comment by rowleya** [comment]
Not sure - it was only a merge into the merge branch in any case i.e. not into master.  I am still hoping the merged branch gets looked at before going in to master.  Note that the code hadn't changed, it was literally the ability to compile with GNU.  I also set the default to the arm tools as before to be on the safe side in any case, and updated the release.sh to ensure that it was the ARM tools that were used for the release.

**Comment by mundya** [comment]
> I am still hoping the merged branch gets looked at before going in to master.

As someone who relies very much on this working can I **strongly** request that code reviews are actually done in this project? Please.

**Comment by rowleya** [comment]
I would agree and normally they are before pulls to master much more thoroughly.  This is still very much a "getting it all working" branch though, so the quality is less important (and this is really just a Makefile change which doesn't change anything if you compile with arm).

**Pull request merged**
