### PR TITLE
Add link to info

### PR DESCRIPTION
**Pull request by rowleya**
This simply adds the "link to root" to the chip info command, where this link is the link identified in the P2P table that packets should be sent to to get to the root chip.  This allows others to quickly identify the tree of chips for sending signals, and so allows us to remove chips when a chip in the path is down.

### CODE REVIEW

**Review by lplana — APPROVED** [review]

**Comment by lplana** [comment]
There is a branch called 'fix_for_armcc+add_link_to_info'. Is it related to this PR?

**Comment by rowleya** [comment]
I forgot to delete it but will now (it was for testing before the other merge)

**Comment by lplana** [comment]
Strictly speaking, this is a backwards-incompatible change that would require a version number change to '4.0.0'.

I cannot assess the impact of the change to SpiNNTools if we don't change the version number. What should we do?

**Comment by rowleya** [comment]
I think it could be considered a "new feature".  This is because it *shouldn't* break existing things using it; that does depend on those things not relying on the full returned packet size from the info command though...  We did have this issue before with rig and they ended up not relying on the full packet size so it should work there at least, and of course our own tools have been updated (and older versions should still work actually because I don't think we relied on packet size there either).

**Pull request merged**
