### PR TITLE
Improved chip info

### PR DESCRIPTION
**Pull request by rowleya**
Upped version number, made requests from 255, 255 respond with the correct SCP address and added Ethernet information (nearest p2p id and IP address) to the chip_info response

### CODE REVIEW

**Comment by mossblaser** [comment]
Looks sensible to me!

Would you mind if I revert the whitespace-only changes to make the diff of the PR and also the blame-history more useful?

**Comment by rowleya** [comment]
If you must, although I actually prefer the white space in this format (spaces rather than tabs).  Note that you can add "w=0" to the end of the URL to see the changes without the white space (another hidden wonder of github)

**Comment by mossblaser** [comment]
...actually, sorry, one more thought: this branch probably isn't the right place to bump the version number since no release is planned for its merging.

> I actually prefer the white space in this format (spaces rather than tabs).

I prefer that style too but sadly the codebase has an existing style and changing it ad-hoc unfortunately makes the formatting inconsistency worse throughout.

> Note that you can add "w=0" to the end of the URL to see the changes without the white space (another hidden wonder of github)

Unfortunately the per-line "blame" history gets trampled by whitespace changes which is my main objection to changing things.

**Comment by rowleya** [comment]
By all means revert the white space changes.  The version number need to be kept consistent for the Python code unfortunately, otherwise people are going to run 2.1.0 and get odities.  I would suggest bumping the version number in some way as soon as changes are made in actual fact and keeping this until release (this is normal practise, although usually you get a post-fix e.g. -dev or -alpha, but I don't think the version number supports this; I also note the irony that I don't do this in other modules).

**Comment by mossblaser** [comment]
> The version number need to be kept consistent for the Python code unfortunately, otherwise people are going to run 2.1.0 and get odities. I would suggest bumping the version number in some way as soon as changes are made in actual fact and keeping this until release (this is normal practise, although usually you get a post-fix e.g. -dev or -alpha, but I don't think the version number supports this;

A -dev postfix sounds like the right solution.

Though the numerical version field can't cope with it, the string-based version number in SLLT_VER_STR probably can. (See include/version.h). Dropping this version number into the main merge branch is probably a good way to go.

What do you think?

**Comment by rowleya** [comment]
This is fine if readable from the sver command, otherwise it isn't much help...

**Comment by mossblaser** [comment]
> This is fine if readable from the sver command

I believe it is :)

**Comment by mossblaser** [comment]
I have rebased the changes from this branch into #14. @rowleya do you mind if I close this branch?

**Comment by rowleya** [comment]
The new pr seems to be missing the change to report the correct scp address in the response.  This isn't critical but maybe should be its own pr?

**Comment by mossblaser** [comment]
> The new pr seems to be missing the change to report the correct scp address in the response.  This isn't critical but maybe should be its own pr?

I was puzzled by that but it appears that this PR also lacks the change unless I've misread the diff so I presumed it had been reverted following our discussion? I don't have strong feelings about this so yes; a new PR would be good if you wouldn't mind and would like to keep the change.

Shall i close this PR then?

**Comment by rowleya** [comment]
I was investigating a way of changing the white space (as at some point we need to declare this standards compliant in some form) without changing the blame history.  Although this is possible, it isn't actually needed, as git can handle blame without white space (git blame -w, and even git blame -w -M which allows for moved lines).  On this basis, I would be less convinced that we need the other branch.  That said, this PR does more than it says it should do, in that it also updates the whitespace as well as a number of other things.  Therefore, I am happy to close this and use the other PR, and open a new PR for the other changes as well.

**Comment by rowleya** [comment]
There is a small issue with the version number changes and backwards compatibility with rig.  If we add the -dev extension, rig will fail to parse the string into ints.  Is this a real problem, or are you happy to cope with it?

**Comment by mossblaser** [comment]
This is shortsightedness in rig so more than happy. As is unpacking extra
chip info fields (I had a look ;) and it would break :P _slaps wrist_.)

**Comment by mossblaser** [comment]
For reference these bugs are/will-be fixed in Rig once project-rig/rig#247 (fixing chip_info forward-compatibility) and project-rig/rig#248 (fixing version number parsing) are merged and released. This will probably be some time tomorrow. Thanks for finding these, @rowleya !

**Comment by mossblaser** [comment]
For reference, Rig v1.4.0 has been released, fixing these two issues.

**Pull request closed without merging**
