### PR TITLE
Fix makefiles

### PR DESCRIPTION
**Pull request by rowleya**
Fixes some issues with the Makefiles spotted by Luis.  Also includes some rationalisation of the Makefiles to hopefully make some things easier to follow (if you can follow a Makefile anyway ;).  This makes the default compile flag for the api and sark Ospace or Os (for ARM and GNU tools), but allows overriding by specifying a APIOPT or SARKOPT flag.

### CODE REVIEW

**Comment by mossblaser** [comment]
When building an application using these makefiles, which (if either) of the APIOPT or SARKOPT flags should be used to control build flags on the application? (Or should you just use CFLAGS)?

**Comment by rowleya** [comment]
APIOPT and SARKOPT should only be used for changing the build optimisation level of the API or SARK respectively.  Use CFLAGS for the application build flags.

**Comment by rowleya** [comment]
ST has given his approval for this.  Does anyone else have any comments or issues before I merge it?

**Comment by mossblaser** [comment]
LGTM!

**Comment by lplana** [comment]
Merge on! -lap

---

**Pull request merged**
