### PR TITLE
The great spinnaker_tools merge of 2016

### PR DESCRIPTION
**Pull request by mossblaser**
This PR has been created to help track the progress of this long-running effort to merge the changes made to SARK/SpiNN1 into spinnaker_tools v2._._ codebase. This merge, once complete, should make this repository the definitive version of "spinnaker_tools" ending years of confusion...

Note that this effort has been lead by, and is almost entirely the hard work of @rowleya (@mossblaser just created this PR).

Remaining checklist (please update as appropriate)
- [x] Initial merge of the code, makefiles etc.
- Validation of SC&MP, SARK and API, build functionality
  - [x] Sanity check by ST
  - [x] Sanity check all demo applications
  - [x] Sanity check against Rig, Network Tester and other assorted tools.
  - [x] Sanity check against SpyNNaker, SpiNNMan and friends
  - [x] Sanity check against PyNN_SpiNNaker (tasked to @neworderofjamie)
  - [x] Sanity check against Nengo_SpiNNaker (tasked to @mundya)
- [x] Add fields to cmd_info essential for use with SpiNNMan (awaiting merging in #14)

### CODE REVIEW

**Comment by rowleya** [comment]
@neworderofjamie and @mundya - let us know if you encounter any problems or need any help with testing

**Comment by rowleya** [comment]
I am pushing this again as this merge is now holding up other things.  From our recent talks, you guys seemed happy that you only rely on rig for most things, and rig appears to be fine with this version of spinnaker_tools.  Note however that it will have a knock-on effect on your binary builds.  If you don't have time to look at this, but are happy with every one else's testing in general, and are happy for this to become the standard spinnaker_tools, please tick the box...  Again, if you are having issues or need help, please ask!

**Comment by neworderofjamie** [comment]
Sorry about this - I have checked both Nengo SpiNNaker and my PyNN
SpiNNaker and (after some Makefile fiddles) both would appear to work
correctly with the merged tools. @mundya -
https://github.com/project-rig/nengo_spinnaker/pull/124

**Comment by mossblaser** [comment]
Excellent :) looks like things are nearly ready to go then! @mundya are you happy to continue given @neworderofjamie 's proposed patch?

@rowleya release notes look great :) Thanks!

**Pull request merged**
