### PR TITLE
fix_additional_section_on_divide

### PR DESCRIPTION
**Pull request by rowleya**
Ignore the additional section (.ARM.exidx) that seems to come when using divide.  Note that discarding this section seems to have no effect at all on the ability to divide.

### CODE REVIEW

**Comment by dr-david-lester** [comment]
Andrew, Luis,

It might be worth testing an actual divide by zero, before you categorically deny a problem with the fix you’ve pushed.

Dave

On 15 Nov 2016, at 15:31, Andrew Rowley <notifications@github.com<mailto:notifications@github.com>> wrote:

Ignore the additional section (.ARM.exidx) that seems to come when using divide. Note that discarding this section seems to have no effect at all on the ability to divide.

---

You can view, comment on, or merge this pull request online at:

  https://github.com/SpiNNakerManchester/spinnaker_tools/pull/34

Commit Summary
-   Ignore the additional section that seems to come when using divide

File Changes
-   M tools/sark.lnkhttps://github.com/SpiNNakerManchester/spinnaker_tools/pull/34/files#diff-0 (5)

Patch Links:
-   https://github.com/SpiNNakerManchester/spinnaker_tools/pull/34.patch
-   https://github.com/SpiNNakerManchester/spinnaker_tools/pull/34.diff

**Comment by rowleya** [comment]
It returns 0 for divide by 0 - I have added some error handlers that seem to fix it.  Note that you still seem to need to ignore the additional section or else it gets added anyway.

**Comment by rowleya** [comment]
I should add that it now RTEs on divide by 0 with an RTE_DIV0 error (which was already available).  I should also add that this same fix seems to work on the ARM compiler as well.

**Comment by dr-david-lester** [comment]
Would have preferred MAXINT and MININT to represent +/- \infty for signed fix points, MAXINT, 0 for unsigned. Oh well.

D.

**Comment by rowleya** [comment]
With the fix, you get RTE, so it never returns a value.  The code for the __aeabi_idiv0 was just a return statement if you don't add your own!

**Comment by rowleya** [comment]
The code has now been updated so that the .ARM.exidx section is included in the ELF.  It is still not included in the APLX.  The reasoning is that this section is only for debug, so it isn't needed by the aplx, only by the ELF when used in gdb.

Additionally, the __aeabi_[il]_div0 functions are now compiled with ARM rather than thumb.  This makes the link to the functions more direct as the GNU division code is ARM compiled, not thumb.

**Comment by rowleya** [comment]
I have now tested this and it doesn't seem to break anything in the neural code, and division by 0 results in RTE on some test code.

**Comment by rowleya** [comment]
Now also tested with various gcc versions, including the currently recommended version for Linux (CodeSourcery 4.7.3).

**Pull request merged**
