### PR TITLE
Remove compiler optimisation flags from default build.

### PR DESCRIPTION
**Pull request by mossblaser**
This enables easier per-use specification of such flags (e.g. by adding things
to CFLAGS).

### CODE REVIEW

**Comment by rowleya** [comment]
Just looking at this - this only really affects the compilation of SARK and the api.  Is this what you intended?  

I am opening another pull request with some other Makefile changes - this includes this change, but also has some other things.

**Comment by mossblaser** [comment]
> Just looking at this - this only really affects the compilation of SARK and the api. Is this what you intended?

Aside from SC&MP are there other builds I've missed?

Thanks!

**Comment by rowleya** [comment]
Well, it affects everything from that point on I guess i.e. anything that uses SCAMP and SARK.  I got the impression you were having issues with a particular build, and it was down to this flag being set.  I have no issue removing the flag (although replacing with a default might be nice - see my other branch for that ;), but just wanted to check what the issue was...

**Comment by mossblaser** [comment]
> I got the impression you were having issues with a particular build

Correct; this was causing issues with network tester which relies quite heavily on -O3 optimisations being used and some GCC versions seem to get confused when -O3 and -Os appear simultaneously.

**Comment by rowleya** [comment]
Yes, GCC needs only one flag, whereas arm can have both I believe.  I presume that this builds using LIB=1 then or does it need O3 on the SARK and api build?

**Comment by mossblaser** [comment]
This change is incorporated in #19, closing this PR.

**Comment by mossblaser** [comment]
> Yes, GCC needs only one flag, whereas arm can have both I believe. I presume that this builds using LIB=1 then or does it need O3 on the SARK and api build?

Rather irritatingly it requires -O3 for SARK and the API too. Unfortunately this makes life unpleasant since to build network tester you essentially need to make a "custom" -O3 build of the API/SARK first. No nice and simple solutions to this issue come to mind, sadly...

In commercial microcontroller libraries I've seen the approach taken is to have the library Makefile compile several versions of the library, for example providing a debug build and a release build. The suggestion is then to link against the appropriate version in your application Makefile.

I think for the moment, given the rarity of this situation the "do nothing and force the network tester developer to rebuild the API/SARK" is the path of least complexity and risk of breaking things.

**Comment by rowleya** [comment]
No problem - this is what I thought.  I guess we could allow the specification of the destination of the libraries to be fluid, and then the network tester could at least then just call the Makefile with a different destination and optimisation flags... just an idea :)

**Comment by mossblaser** [comment]
Certainly :). That said, as I say, this is probably worth saving for the future if/when more applications have this problem.

**Pull request closed without merging**
