### PR TITLE
Fix p2p link blacklisting

### PR DESCRIPTION
**Pull request by mossblaser**
This branch fixes a couple of bugs relating to blacklisting not being applied when constructing P2P routes.
- [x] ~~Sanity~~ correctness check by Luis (who spotted this)
- [x] Sanity check by ST
- [x] Sanity check by @rowleya

As an aside, along with be8fb58 this has been quite the flurry of silly mistakes in P2P blacklisting support. I think I may try and build a test suite for some of this stuff since it is quite sorely needed.

### CODE REVIEW

**Comment by rowleya** [comment]
Looks sane to me :).

**Comment by lplana** [comment]
I think that it's correct. Sane?, I don't know.  -lap

---

**Comment by Steve-Temple** [comment]
Looks good to me too...

**Comment by mossblaser** [comment]
Thanks very much all!

**Pull request merged**
