### PR TITLE
Stablise the drift calculation

### PR DESCRIPTION
**Pull request by rowleya**
The drift calculation was a bit unstable, particularly for chips on the same board, where it could vary between chips.  By some simple tweaking, this makes the calculation more stable in general, both over a single board and in particular means no drift is detected on the Ethernet board at all.  Interestingly, where there is a drift from the boot-chip-board, this does dither about a bit.  This could be due to either the resolution of the timer not quite being enough, or else something that happens in the board-to-board links.

In any case, this produces vastly improved results on some tests that were in some cases a bit unstable.

Tested by SpiNNakerManchester/sPyNNaker8#489, which depends on SpiNNakerManchester/SpiNNMan#223, which is where the rebuilt SCAMP is held.

### CODE REVIEW

**Comment by lplana** [comment]
I'm happy with the changes.

It would be interesting to find out if the board-to-board links have an impact, as suggested in the comment above. I'm not sure if there is a lot that can be done, but at least we should be aware of any issues.

**Review by lplana — APPROVED** [review]

**Comment by lplana** [comment]
This pull request seems to be showing symptoms of multiple personalities:
- at the very top is says Checks 0
- at the bottom it says all checks have passed: 1 successful check.

I assume that "check" is overloaded and that the inconsistency is related to the adoption of github "actions".

Could somebody please clarify this and also clarify if "actions" will replace Jenkins continuous integration tests?

Many thanks.

**Comment by rowleya** [comment]
I think "Checks" is referring to "github actions checks".  Although there isn't a specific need to replace Jenkins with actions (as that is local to our servers anyway), I may make this move for consistency.  I think this branch needs master merging in to get the actions checks that are in place though, as the Jenkins check doesn't do any code style or documentation checking.  I will do this shortly...

**Comment by lplana** [comment]
Ta.

**Comment by rowleya** [comment]
This is all up-to-date and all tests are now passing

**Pull request merged**
